workflows:
  android:
    environment:
      groups:
        - leave-app-secrets
        - test_group
    # cache:
    #   cache_paths:
    #     - $CM_BUILD_DIR/node_modules
   
    scripts:
      - name: Export Environment Variables
        script: |
            echo "Exporting environment variables to .env file"
            env > .env.qa
      - name: export env variables to .env file
        script: |
          echo "Exporting environment variables to .env file"
          > .env.dev  # Create an empty .env.dev file

          # Loop through the environment variables and export them with their values
          env | grep -E "^ENV_" | while IFS='=' read -r key value; do
            echo "${key}=${value}" >> .env.dev
          done
    #   - name: Install Yarn Dependencies
    #     script: |
    #       yarn install
    #   - name: Install Fastlane    ....
    #     script: gem install fastlane -N

      # - name: Build Android APK
      #   working_directory: android
      #   script: | 
      #    bundle install
      #    bundle exec fastlane build
    # artifacts:
    #   - app/build/outputs/**/**/*.apk
