workflows:
  my-workflow:
    scripts:
      - name: Install Yarn Dependencies
        script: |
          yarn install
      - name: Install Fastlane
        script: gem install fastlane -N
          
      - name: Build Android APK
        working_directory: android
        script: fastlane build
    artifacts:
      - app/build/outputs/**/**/*.apk
