default_platform(:android)

desc "Build Android APK"
lane :build do

  UI.message(ENV["ENV_VAR_1"])
  
  # variable_value = lane_context[SharedValues::ENV_VAR_1]
  # UI.message("VARIABLE_NAME: #{variable_value}")
#   gradle(task: "clean", project_dir: ".")
# gradle(
# task: "assemble",
# build_type: "Release"
# )

# firebase_app_distribution(
#       app: "1:763187060841:android:8ddbff9ed62f90599802f8",
#       groups: "leave-app-internal-testers",
#       android_artifact_type:"AAB",
#       cli:"1//0g-Kxuf_RzIsQCgYIARAAGBASNwF-L9Ir-pOIfTIAnq8JKyFOu1T1selM_h7h90i2E1SlSRnreNhkWOfAxdCjZfasmBV0_gQAQmQ"
#       android_artifact_path: "./app/build/outputs/bundle/devRelease/app-dev-release.aab",
#       release_notes: "Version 1.0.0",
#      // service_credentials_file: "./app-distribution-service-account.json",
#       debug: false,
#     )


end